#include "pch.hpp"
#include "utils/variant.hpp"
#include <fstream>

#include "variantLoadScope2.hpp"
#include "VariantParser.hpp"

namespace utils
{

	//////////////////////////////////////////////////////////////////////////
	bool Variant::load2(const char *fileName, std::string *errors)
	{
		boost::filesystem::path p = boost::filesystem::absolute(fileName);
		std::ifstream in(p.string().c_str(), std::ios::binary);
		if(!in)
		{
			if(errors)
			{
				*errors += "file not found: ";
				*errors += fileName;
				*errors += "\n";
			}
			return false;
		}

		bool parseResult;

		{
			std::vector<char> buffer;
			in.seekg(0, std::ios::end);
			buffer.resize(in.tellg());
			in.seekg(0, std::ios::beg);


			const char *first;
			const char *last;
			if(!buffer.empty())
			{
				in.read(&buffer[0], buffer.size());
				in.close();
				first = &buffer[0];
				last = first + buffer.size();
			}
			else
			{
				first = "";
				last = first + 0;
			}

			VariantLoadScope2 scope(fileName, first, last, errors);

			VariantLexerTraits::InputStreamType input((const unsigned char *)fileName, ANTLR_ENC_8BIT);
			VariantLexer lxr(&input); // TLexerNew is generated by ANTLR
			VariantParserTraits::TokenStreamType tstream(ANTLR_SIZE_HINT, lxr.get_tokSource() );
			VariantParser psr(&tstream); // TParserNew is generated by ANTLR3

			psr.start();

			parseResult = true;

			if(parseResult)
			{
				if(first != last)
				{
					//boost::spirit::info what(std::string("end"));
					//scope.error(&buffer[0], last, first, what);
				}
			}

			if(scope.errorWas())
			{
				parseResult = false;
			}
			if(parseResult)
			{
				this->swap(scope.getValue());
			}
		}


		return parseResult;
	}


}
