// Component configuration file automatically generated as ComponentConfig.h
// by ConfigureComponent on Thu Sep 21 14:32:46 2000


// COM UUID-s, names and progID



// TODO: Modify these macros
// !!! ALWAYS REPLACE THE UUID STRINGS WITH NEW UNIQUE IDS (These new GUIDs can be generated by the guidgen tool)
#define TYPELIB_UUID "CAB05A05-F6A5-4f89-91F5-81826E958A5C"
#define TYPELIB_NAME "MGA Decorator TypeLibrary (R3Decorator)"
#define COCLASS_UUID "C8054B76-4760-4a4d-8B03-5990DF0B8862"
#define COCLASS_NAME "MGA Decorator CoClass (R3Decorator)"
#define COCLASS_PROGID "MGA.Decorator.R3Decorator"

#define CONSTOLESTR(X)		OLESTR(X)


// This name will appear in the popup window for interpreter selection.
#define DECORATOR_NAME "R3Decorator"



