
#SET_PROPERTY(DIRECTORY "." PROPERTY COMPILE_DEFINITIONS_DEBUG "${COMPILE_DEFINITIONS_DEBUG}")
#SET_PROPERTY(DIRECTORY "." PROPERTY COMPILE_DEFINITIONS_RELWITHDEBINFO "${COMPILE_DEFINITIONS_RELWITHDEBINFO};LOG4CPLUS_DISABLE_DEBUG")
#SET_PROPERTY(DIRECTORY "." PROPERTY COMPILE_DEFINITIONS_MINSIZEREL "${COMPILE_DEFINITIONS_MINSIZEREL};LOG4CPLUS_DISABLE_INFO")
#SET_PROPERTY(DIRECTORY "." PROPERTY COMPILE_DEFINITIONS_RELEASE "${COMPILE_DEFINITIONS_RELEASE};LOG4CPLUS_DISABLE_INFO")
