
#######################################################################################
# SETUP_BIN_OUT

MACRO(SETUP_BIN_OUT target dst)

	GET_TARGET_PROPERTY(TARGET_LOCATION ${target} "LOCATION")

	IF("${ARGV2}" STREQUAL "")
		GET_FILENAME_COMPONENT(TARGET_NAME ${TARGET_LOCATION} NAME_WE)
	ENDIF()

	IF(NOT "${ARGV2}" STREQUAL "")
		SET(TARGET_NAME ${ARGV2})
	ENDIF()

	GET_TARGET_PROPERTY(TARGET_LOCATION ${target} "LOCATION")
	GET_FILENAME_COMPONENT(TARGET_EXT ${TARGET_LOCATION} EXT)

	FILE(TO_NATIVE_PATH ${TARGET_LOCATION} FROM)

	IF(MSVC)
		FILE(TO_NATIVE_PATH "${ROOT_DIR}/$(ConfigurationName)/${dst}/${TARGET_NAME}${TARGET_EXT}" TO)
	ELSE()
		FILE(TO_NATIVE_PATH "${ROOT_DIR}/${CMAKE_BUILD_TYPE}/${dst}/${TARGET_NAME}${TARGET_EXT}" TO)
	ENDIF()

	ADD_CUSTOM_COMMAND(
		TARGET ${target}
		POST_BUILD
		COMMAND ${CMAKE_COMMAND} -E copy "${FROM}" "${TO}")

	#ADD_CUSTOM_TARGET(
	#	"${target}_${dst}_${TARGET_NAME}"
	#	${CMAKE_COMMAND} -E copy "${FROM}" "${TO}"
	#	DEPENDS ${target})
ENDMACRO()
