///////////////////////////////////////////////////////////////////////////
// ComponentConfig.h, component configuration parameters.
//
// Initially generated by the component wizard. Feel free to manually edit.
///////////////////////////////////////////////////////////////////////////

// Component framework type
#define BON2COMPONENT

// COM UUID-s, names and progID
#define TYPELIB_UUID "E69FC123-5EDB-4940-AA3D-8185FCF203E2"
#define TYPELIB_NAME "MGA Interpreter TypeLibrary (R3Interpreter)"
#define COCLASS_UUID "7B2C7F02-4F79-4697-9DF5-37430251FE11"
#define COCLASS_NAME "MGA Interpreter CoClass (R3Interpreter)"
#define COCLASS_PROGID "MGA.Interpreter.R3Interpreter"

#define COCLASS_UUID_EXPLODED1  0x7b2c7f02
#define COCLASS_UUID_EXPLODED2   0x4f79
#define COCLASS_UUID_EXPLODED3   0x4697
#define COCLASS_UUID_EXPLODED4   0x9d
#define COCLASS_UUID_EXPLODED5   0xf5
#define COCLASS_UUID_EXPLODED6   0x37
#define COCLASS_UUID_EXPLODED7   0x43
#define COCLASS_UUID_EXPLODED8   0x2
#define COCLASS_UUID_EXPLODED9   0x51
#define COCLASS_UUID_EXPLODED10  0xfe
#define COCLASS_UUID_EXPLODED11  0x11


// This name will appear in the popup window for interpreter selection.
#define COMPONENT_NAME "R3Interpreter"


// This text will appear in the toolbar icon tooltip and in the menu.
#define TOOLTIP_TEXT "R3Interpreter Interpreter"

// This macro determines the component type (addon vs. interpreter):
#define GME_INTERPRETER

// The name of the paradigm(s). The GME will use this component
// for this paradigm. Separate the names of paradigms by commas.
#define PARADIGMS "R3Meta"


#define BON_ICON_SUPPORT

// not defined: #define BON_CUSTOM_TRANSACTIONS

// not defined: #define REGISTER_SYSTEMWIDE
